apiVersion: v1
kind: Service
metadata:
  name: firefox-send
  namespace: oliverni
spec:
  clusterIP: None
  selector:
    app: firefox-send
  ports:
    - port: 1443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox-send
  namespace: oliverni
  labels:
    app: firefox-send
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firefox-send
  template:
    metadata:
      labels:
        app: firefox-send
    spec:
      containers:
        - name: firefox-send
          image: mozilla/send:latest
          ports:
            - containerPort: 1443
          env:
            - name: S3_BUCKET
              value: oliverni
            - name: S3_ENDPOINT
              value: us-east-1.linodeobjects.com
            - name: REDIS_HOST
              value: localhost
            - name: BASE_URL
              value: https://send.oliver.ni
            - name: NODE_ENV
              value: development
            - name: FXA_REQUIRED
              value: "false"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-creds
                  key: secret-key
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "400m"
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
