apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-auth
  namespace: bmt
spec:
  encryptedData:
    .dockerconfigjson: AgAlihxJtTqCIwIrBb49mdEoCfbE/2/NXWUOhfB+Lo5dklHhfvFH+iHLGHboLFqOi/D8vuId67MakaJ1EgLek9PvxoQKT94X/eKIfcz38a42XdxdBdo6pGTJBU/H+Kkpzt9wQaS4mEREbkjN4ywyy4ThKodSfbIloiDfv0qROYCrOW7dlk0xB/bcLEPkhXrluLDqtnmKyqgbC1BGSaOfGxAlMtCPPUQEI6ZSPHIfYR4oEJn0ARdDzwMdc/nZqxOMIeefbI867guQY8AWleqkr0lutd6PtE4sMDUhe9HpQplQ1HS6OTupU/4QQCgky7b/7mYgLyw6xv0r/+8cxpYBipRra/ZQQCG0MuUxgbEBCeD3WGx/gqtf3qb1b0eWfGt97UdTyKUzqk8VG2zBId01+6zlLEzqg6aZndKPu5xNoHn1b5eNsfL21BhpTCVQQMMyKMAKrkoTq2CltSdrJLScDqm89XQdV94IvWbA1fSQhqgTucEIzr5h05JnylWc81XInF0r+6m1KeaMCsIaJwiyh/uuwj31AKYyKYcFavlkH5SeaNjHRJGQ62iy6WgPhqImwep8Vdi5fjHeY3fZQouBRPixx+77UD3oHT3apthNErI7oI14RF3U3pUnwWQy9SvlBCAeZnpc5RmgHutvdWQ8K0+wazxxdrqHuySr7Azb4qzabkbD0cmV/E4hnbGYlyVlBkZqGNqZeenr3Br8W0j0J/gOpuLQwiBpzqKKxVR0nJDzkLtcAwMznwQkKKH87gaaGjKcPyCc0N1iJakb8cLHju5+95wCwYED7hlSz6x0hPQOTxupuMWaKk3ErNJk3ooct5hHqquoX3g=
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-auth
      namespace: bmt
    type: kubernetes.io/dockerconfigjson
