apiVersion: v1
data:
  DISCORD_CLIENT_ID: '1108551511233011764'
  DISCORD_GUILD_ID: '786701065856221205'
  DISCORD_REDIRECT_URI: https://pw.berkeley.mt/api/auth/discord/callback
  DISCORD_REQUIRED_ROLE_IDS: '1532248559892566016'
  GIT_PUSH: '1'
  GIT_REPO_URL: https://github.com/berkeleymt/bmt-2026.git
kind: ConfigMap
metadata:
  name: webview
  namespace: bmt-webview
