apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webview
  namespace: bmt-webview
spec:
  destination:
    create: true
    name: webview
    type: Opaque
  mount: hfym-ds
  path: bmt-webview/webview
  type: kv-v2
