apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: jirav
  namespace: bmt-jirav
spec:
  destination:
    create: true
    name: jirav
    type: Opaque
  mount: hfym-ds
  path: bmt-jirav/jirav
  type: kv-v2
