apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guts-scoreboard-data
  namespace: bmt-guts-scoreboard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
