apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: stickers
  namespace: bmt-stickers
spec:
  destination:
    create: true
    name: stickers
    type: Opaque
  mount: hfym-ds
  path: bmt-stickers/stickers
  type: kv-v2
