apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ag-assets
  namespace: atomicgrader
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: cephfs-nvme-retain
