apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mathematician-mash-basic-auth
  namespace: bmt
spec:
  destination:
    create: true
    name: mathematician-mash-basic-auth
    type: Opaque
  mount: hfym-ds
  path: bmt/mathematician-mash-basic-auth
  type: kv-v2
