apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: swire2
  namespace: bmt
spec:
  destination:
    create: true
    name: swire2
    type: Opaque
  mount: hfym-ds
  path: bmt/swire2
  type: kv-v2
