apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: puzzle-hunt
  namespace: bmt
spec:
  destination:
    create: true
    name: puzzle-hunt
    type: Opaque
  mount: hfym-ds
  path: bmt/puzzle-hunt
  type: kv-v2
