apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: swire2-ingress
  namespace: bmt
spec:
  rules:
  - host: swire-new.berkeley.mt
    http:
      paths:
      - backend:
          service:
            name: swire2
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - swire-new.berkeley.mt
    secretName: swire2-ingress-tls
