apiVersion: apps/v1
kind: Deployment
metadata:
  name: contestdojo-verifier-bot
  namespace: bmt-contestdojo-verifier-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contestdojo-verifier-bot
  template:
    metadata:
      labels:
        app: contestdojo-verifier-bot
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: contestdojo-verifier-bot
        image: ghcr.io/berkeleymt/contestdojo-verifier-bot:latest
        name: contestdojo-verifier-bot
        ports:
        - containerPort: 4887
        resources:
          limits:
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 64Mi
      imagePullSecrets:
      - name: ghcr-auth
